---
driver:
  name: digitalocean

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:<% %w{centos-6-5-x64 centos-5-10-x64}.each do |p| %>
- name: <%= p %><% end %>

suites:
- name: default
  run_list:
  - recipe[oracle-xe_test]
  - recipe[oracle-xe]
  attributes:
    oracle-xe:
      url: <%= ENV['ORACLE_XE_RPM_URL'] %>
    yum:
      main:
        gpgcheck: false
