driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-6

suites:
- name: default
  run_list: ["recipe[oracle-xe_test]", "recipe[oracle-xe]"]
  attributes: 
    oracle-xe:
      url: https://d19aqaq2etoqgb.cloudfront.net/oracle-xe-11.2.0-1.0.x86_64.rpm
