sudo: required
dist: trusty
addons:
  apt:
    sources:
    - chef-current-trusty
    packages:
    - chefdk
install: echo "skip bundle install"
branches:
  only:
  - master
services: docker
env:
  matrix:
  - INSTANCE=default-centos-6
  - INSTANCE=default-centos-7
  - secure: SRXrFQgm+kRZ0VsW2uO3yJLfe7a3DnlpivUgm460HNedSMHdiBqvQyFYSQ/5+KZyUYohUqizMHH7h0h+tdOvmS1nLHAOE4EMfTHV6LlNL5ZQNPQLDedlzQXduk/1UCoCS3v2qi+GFeK7LNm70PWM7CjryCtjEmu9/IMUKlMXLdk=
before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables
  -N DOCKER )
- eval "$(chef shell-init bash)"
- chef --version
- cookstyle --version
- foodcritic --version
script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}
matrix:
  include:
  - script:
    - chef exec delivery local all
    env: UNIT_AND_LINT=1
